### ISSUE TITLE
Use qualitative descriptions for effect strengths

### ISSUE THREAD

**Issue by frnsys** [frnsys/half_earth#104]
Instead of e.g. "increases extinction rate by 1" it's more meaningful to say "increases extinction rate by a little".

**Comment by entityleak** [comment]
Also for process intensity : High Intensity / Low Intensity. these could also be represented by an icon. Something different to the bar would be good

**Comment by frnsys** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/1059947/153642752-cb2c3642-4c83-4e6f-8133-477e81d92c9e.png)
![image](https://user-images.githubusercontent.com/1059947/153642763-886f9752-ffeb-477b-b395-d32c3576dbdb.png)
![image](https://user-images.githubusercontent.com/1059947/153642774-840c855a-10ab-4b95-b398-5fb728bee65e.png)
