### ISSUE TITLE
Image compression and rendering

### ISSUE THREAD

**Issue by entityleak** [frnsys/half_earth#106]
compressed `.jpgs` with default browser scaling makes them blurry and mushy, working against the crisp pixelated art style.

Solution :
- use `.pngs` that are preloaded 
- set global css style for images that renders pixels without blurring https://caniuse.com/css-crisp-edges

**Comment by entityleak** [comment]
I thought that changing to Riemersma would fix this issue where it seems like the pixels kind of 'blob' up

Blobbing
<img width="710" alt="Screen Shot 2022-02-11 at 15 39 33" src="https://user-images.githubusercontent.com/21215589/153614557-e80b9f55-0cdb-4848-9a38-9da32bffcda9.png">

Pixeling
<img width="554" alt="Screen Shot 2022-02-11 at 15 39 54" src="https://user-images.githubusercontent.com/21215589/153614568-6260837a-c516-4f0e-bb38-868d907bf4fe.png">

**Comment by frnsys** [comment]
Oh it might because the image is scaled down then rescaled up? That could introduce artifacts
