### ISSUE TITLE
Contentedness stays too high?

### ISSUE THREAD

**Issue by entityleak** [frnsys/half_earth#124]
Haven't extensively tested this but seems like it's hard to put a dent in Contentedness. 

Should have more options for players to take a hit in contentedness in exchange for other benefits - in early game most of the unpop policies are locked

Also- Post-Revolution optimism doesn't go away.

**Comment by frnsys** [comment]
"Post-Revolution Optimism" should probably be renamed, it's really meant to be just the default starting value so it never really goes away...Is "Baseline Contentedness" too boring?

**Comment by entityleak** [comment]
Yeah maybe let's leave it then
