### ISSUE TITLE
Card-tags inside effects can't be clicked on

### ISSUE THREAD

**Issue by entityleak** [frnsys/half_earth#158]
Something to do with the fit text plugin (?) 

<img width="265" alt="Screen Shot 2022-03-08 at 18 25 41" src="https://user-images.githubusercontent.com/21215589/157292011-b9967b74-e9cf-47e6-bb17-1831788615f4.png">

**Comment by frnsys** [comment]
Ah yeah I added that to prevent overflow on smaller browsers, I'll take a look
