### ISSUE TITLE
View results / timeline / history / data of a run after run completion

### ISSUE THREAD

**Issue by sbutler-gh** [frnsys/half_earth#248]
After completing a run (winning or losing), I'd like to be able to view a recap of what I did in that run.  Perhaps the cards played in different planning cycles, when cards were completed, the planning cycle choices for production values.  It could make sense to include this in the share-able post game link, so when you share on social media / with others, they can see what you did as well and people can see different strategies / gameplay runs / etc?

Maybe as a simple implementation, it could be:

_A timeline of completed cards / production changes, which includes the year the card/production change was first played, and later on in the timeline, when the card/production change was actually implemented.  This could also potentially include some visual cue about the card's impact/weight on the run, to see how impactful it was in that context of that run._  

With something like that, the timeline could share the story of the run and your choices as planner at a glance and scroll.

**Comment by dkniffin** [comment]
To add to this, I'd like to see this even during a run. I often wonder "wait, what happened in that last report?" Seeing a log somewhere of all the things that happened would be great.
