### ISSUE TITLE
Building is extremely hard.

### ISSUE THREAD

**Issue by l3gacyb3ta** [frnsys/half_earth#255]
I have tried to figure this out but I cannot. for the life of me. get the thing. to build. 

I even found that one hidden url with the editor and that changed nothing.

**Comment by frnsys** [comment]
Can you give me any more information on what you tried, what command wasn't working, etc?

**Comment by Phantasus** [comment]
Well, basically following the setup of: ```


# Install JS dependencies
npm install -d

# Install hector-rs
git clone https://github.com/frnsys/hector-rs.git hector/hector-rs
cd hector/hector-rs
bash setup.sh
cd ../../

# Fetch and parse latest content
# Requires `pip3 install pillow`
bash update_content.sh
```

does not work on Archlinux, at least for that platform.

**Comment by frnsys** [comment]
Very late getting back to you, but I've just updated the setup process to be easier (hopefully).
