### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by dvn0** [frnsys/half_earth#260]
Hello - I'd be interested in contributing to the project, but there appears to be no licensing information. I would recommend [AGPL](https://www.gnu.org/licenses/why-affero-gpl.html), but any [popular OSI license](https://opensource.org/licenses/?categories=popular-strong-community) would suffice.

This would allow fans of the book and the game to contribute to and perhaps harbor a community of custom modifications of the game.

Thanks.

**Comment by dvn0** [comment]
Tagging @frnsys and @entityleak

**Comment by frnsys** [comment]
Thanks for the suggestion--just added the AGPL

**Comment by dvn0** [comment]
Thanks much!
