### ISSUE TITLE
update_content.sh tries to call non-existant url

### ISSUE THREAD

**Issue by carys-the-weed-cloud** [frnsys/half_earth#266]
Following the setup steps, upon reaching
`bash update_content.sh`
The script calls the url 
`half-earth-editor.frnsys.com`
but it returns a 404 and looking at the link in a browser also returns nothing but reroutes to the main page of the Francis Tseng blog.

Image Attached.

![ksnip_20231216-021406](https://github.com/frnsys/half_earth/assets/36204825/bc01bbca-489f-4ff6-b8d3-d3ef24b66abe)

**Comment by carys-the-weed-cloud** [comment]
Okay I think this is preventing me from running the editor or doing anything to edit the project, and quite frankly I don't have time to understand and troubleshoot the problem at the moment especially with a package environment as entangled as this one.

I assume the set up being blocked is causing the `npm start` to not start, and thus this entire project just won't work and is unusable unless someone goes in and sorts it out. Would love to see this function yet again so I can edit the game.

**Comment by frnsys** [comment]
Hey, thanks for your interest in the game. The editor is privately hosted at the moment so only a few of us are able to edit the "official" version. But you can also edit the data directly (`editor/data.json`) to modify your copy of the game, or you can run the editor locally (see the `editor` folder). To update using the local editor data, run `just update_local`. I haven't fully tested it, so YMMV but let me know if you run into any further issues.
