### ISSUE TITLE
Error when trying to add 1 to a science project

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#273]
On Firefox, when I tried editing my projects:
Tried to add 1 to the project ("green hydrogen" in this case), but then the game crashed (I think the exact moment the card would have received the additional science) and several errors in the console kept speeding by, utilizing a lot of 1 core of my cpu and lagging firefox. Had to close the tab, couldn't copy an error log.

![image](https://github.com/user-attachments/assets/22b4d288-d166-4b9d-bab3-d9ec8f2009b7)
Image of task manager and the game.

I'll try on Chrome too and comment here.

**Comment by sgitkene** [comment]
It happens in Chrome too, and also with an industry project. I enabled pause on exception in order to be able to copy the error.

```
hes-game.js:642 panicked at hes-game/src/views/cards/mini/project.rs:39:41:
Attempted to get a signal after it was disposed.
warning happened here: hes-game/src/views/cards/mini/project.rs:39:41

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://play.half.earth/pkg/hes-game.js:629:13)
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[6136]:0x242d0f
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[1450]:0x125edb
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[2978]:0x1c3dae
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[5612]:0x23f5fb
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[4113]:0x2013ef
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[2059]:0x1694ca
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[3869]:0x1ee979
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[1568]:0x13122d
    at https://play.half.earth/pkg/hes-game.wasm:wasm-function[1645]:0x13825f
```

![image](https://github.com/user-attachments/assets/5a5d6bc3-4a41-41d5-b605-ae672dd4b03f)
Image of the game, paused in the debugger just after the error happened when trying to add 1 to "Expand Recycling".

**Comment by frnsys** [comment]
Thanks for reporting this. There's another scanning bug that I'm currently investing but I believe I have a fix for this one that'll go out after I figure out #274.
