### ISSUE TITLE
Game does not advance at the end of year 2022

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#274]
On Chrome, after clicking "ready", the progress bar at the bottom went by to advance to the next year, but nothing happened. The game seems stuck at this screen. I can still interact with the menu and the clickable fields for temperature, happiness, etc, but the game just doesn't go on. Clicking "skip" doesn't do anything I could tell. I can drag around the globe and it behaves normally I think. There are no errors in the console.

![image](https://github.com/user-attachments/assets/b999b788-79c6-4ed6-aeef-1e6688170875)
Image of the game presumably stuck at the end of 2022.

I'll try again on Firefox too.

**Comment by sgitkene** [comment]
Same on Firefox:

![image](https://github.com/user-attachments/assets/848069be-9f7b-4286-80dd-6342259043af)
Image of the game presumably stuck at the end of 2022.

**Comment by sgitkene** [comment]
When I left the break on, it actually pauses due to a caught exception (the debugger doesn't pause when not ticking that box):

![image](https://github.com/user-attachments/assets/a5479c74-e643-44ff-82b1-2f43ec456c36)
Image of when the debugger pauses exectuion due to a caught exception.

**Comment by frnsys** [comment]
I believe this should be fixed now. Thanks again for the report! The whole game was recently re-written so bug reports are a big help.
