### ISSUE TITLE
Game stops running at the end of 2026

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#276]
The game freezes up at the end of 2026, after showing a few events. Menu items are still clickable and display the small tooltip (e.g. temperature "The current global temperature anomaly...") when clicked. The "skip" button just does nothing. The toasts about floods at the bottom are frozen. The globe is still animated and one can turn it around.

![image](https://github.com/user-attachments/assets/37eceb2a-1f2b-4d58-b50f-edb2aa87a35e)
Image containing the frozen game state and the console showing no errors.

I'll retry that with pause on exception enabled.

**Comment by sgitkene** [comment]
Not sure if related, but my projects seem to be in a weird state: They are "passed" but still require a planning cycle? The things they are supposed to unlock were also not unlocked after the first year, so I assume they are not passed.

![image](https://github.com/user-attachments/assets/c287f342-0cc2-487f-95dc-c399a1a1693b)
Image containing the projects in a weird state, having been passed in the last cycle, but still show they require 1 cycle to implement.

**Comment by sgitkene** [comment]
This time around, the globe didn't load properly. I've seen this before, but I think it just looks weird, it doesn't seem to affect anything beyond that. I can't seem to advance the game even when I unpause the debugger and disable the pause on caught exceptions, it just starts maxing out the core again.

![image](https://github.com/user-attachments/assets/e65adfa7-2628-4898-b7b3-fb1a4c6d7930)
Image showing the game frozen by debugger due to a caught exception.

**Comment by sgitkene** [comment]
I managed to arrive at the next screen by clicking skip before the game freezes.

![image](https://github.com/user-attachments/assets/7a6ad422-0672-406a-a1fe-d9e3a0e30734)
Image showing the summary of the last cycle.

**Comment by frnsys** [comment]
Thanks for this report. For the globe texture, I believe it's because the textures are calculated on demand and sometimes it fails. I'm switching to pre-computing all the surfaces so that should take care of that.

I also have a fix for the policies not finishing in the correct time.

I have a few other things I'm working on but I'll try to take a look at the 2026 bug soon.

**Comment by frnsys** [comment]
Ok I have a fix ready for this. I have to step out right now but I'll deploy the changes later tonight. Thanks again!
