### ISSUE TITLE
Production does not update after first cycle

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#277]
I changed my electricity production (-3 coal, -1 petroleum, + 1 nuclear, +1 PV, +2 Terrestrial Wind), which used to work in the first cycle. Also, the tooltip at the bottom said this will require 1 planning cycle. Yet nothing changed, after the first cycle, my changes were still here, waiting to be implemented. There were no errors in the console and no uncaught exceptions I could notice. I can't reliably reproduce this, it doesn't happen every time.

![image](https://github.com/user-attachments/assets/36446f59-6928-4d91-97b4-e01f2f6ccd89)
Image depicting yet to be implemented electricity mix changes from previous cycle.

**Comment by frnsys** [comment]
So far I haven't been able to reproduce it either but I'll keep my eye out for it.

**Comment by sgitkene** [comment]
I made a video but probably commented on the wrong issue: https://github.com/frnsys/half_earth/issues/278#issuecomment-2278232819

There's a timestamp to multiple instances of this happening.
