### ISSUE TITLE
Feminist Science and Technology Studies does not award the 20 science points

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#279]
![image](https://github.com/user-attachments/assets/91edb560-f174-472c-908f-ae532f0637b2)
The policy has been passed successfully.

![image](https://github.com/user-attachments/assets/1374e24a-8504-4e13-9750-a6c7f4a63c28)
The count where I expected to receive the points did not increase.

**Comment by frnsys** [comment]
Thanks, this was a quick fix, should also take care of the Underwater Biosphere problem.

**Comment by sgitkene** [comment]
can't confirm, did not receive research points on the new run after hard-reload and new save.

**Comment by frnsys** [comment]
sorry, haven't deployed the changes yet--trying to fix a few other things first

**Comment by sgitkene** [comment]
it seems to work now 👍
