### ISSUE TITLE
High Density Batteries displays false time saving on other projects

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#282]
![image](https://github.com/user-attachments/assets/e20d7219-c6e6-489a-9918-a301537a0dde)
Battery Storage Network's total development time was 15y, it can't be reduced by 30. Maybe somewhere in the code it says "reduce by factor 2" but then this gets multiplied instead of divided?

**Comment by sgitkene** [comment]
![image](https://github.com/user-attachments/assets/022c1fae-437a-4d00-9005-853101bb748d)
Biosphere 3 research indicates 0 reduction.

**Comment by frnsys** [comment]
This ended up being kind of complicated, for simplicity I'm switching it back to percentages (e.g. "reduces development time by 50%") which is how it was I believe in the previous version.
