### ISSUE TITLE
Changes in production does not go through in first cycle

### ISSUE THREAD

**Issue by maltegartner** [frnsys/half_earth#287]
First cycle: I change production mix in electricity, fuel and crops by removing 20% from one (biofuels 15% and coal 5%, for example) and adding to another (natural 20%). Only 15% of that goes through. In electricity, nothing goes through on the first cycle. 

A note at the bottom says "These changes will tale 1 planning cycle to take effect". It doesn't.

If there's some logic to the game that the changes can't happen after all, it would be interesting to learn something from it - resource need or whatever.

**Comment by sgitkene** [comment]
I had the same issue, see https://github.com/frnsys/half_earth/issues/277

The changes to calorie production (crop and livestock agriculture) don't seem to go through at all.

**Comment by Doctor5555** [comment]
I've been trying the website version out today, and it looks like only one category of production changes per planning cycle, with a priority order of Fuel > Electricity > Crops > Livestock. This means that if you have any changes lined up in Fuel, then nothing else goes through.

In the itch.io version, sometimes things would take longer than suggested to build out or wind down, particularly industrial agriculture would often show as 1 cycle to decrease after the places it had been changed to had built out in actually 1 cycle, but all the categories were built separately.

**Comment by sgitkene** [comment]
I think if the steam/itch.io versions are the "model", there were 5 points _each_ category. Here's a short video what it looks like: https://youtu.be/R3f76gnOrDs

**Comment by frnsys** [comment]
Thanks for the report and the help investigating--i was able to create a test reproducing the problem and have a fix that I'll deploy after getting through some of these other issues
