### ISSUE TITLE
Science point reward from Feminist Science and Technology awarded multiple times

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#288]
![image](https://github.com/user-attachments/assets/2ebfa302-34e8-4a03-a015-8a2fb951999d)
After another cycle, I found that I have been awarded too many science points, probably through the aforementioned project.

**Comment by sgitkene** [comment]
maybe the fix from https://github.com/frnsys/half_earth/issues/279 is working too well?

**Comment by frnsys** [comment]
I believe this was actually due to a different project--I was able to reproduce it with Biosphere 3. If it's the same thing you encountered then I have a fix to deploy soon. thanks for the report!
