### ISSUE TITLE
Emissions on year-end summary don't match the history at the end of the game

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#297]
I think some of the projects' negative emissions are not being counted. I think e.g. DAC may be one of the culprits, as the large discrepancies start appearing with increasing levels of DAC. I attached the entire history too.

<img width="330" alt="2022-2025" src="https://github.com/user-attachments/assets/a2e51c46-7fdb-41f5-8122-c1301243d0a7">

[2025]
political_capital: 100 -> 4
emissions.as_gtco2eq: 51.579174 -> 54.981224 (seems correct)

<img width="305" alt="2025-2030" src="https://github.com/user-attachments/assets/e1783ff9-21db-42a5-82f6-379b93407178">

[2030]
political_capital: 4 -> 0
protected_land: 0.1 -> 0.13333333
emissions.as_gtco2eq: 54.**9**81224 -> 55.31417 (first discrepancy)

[2035] (Forgot to sc)
political_capital: 0 -> 8
protected_land: 0.13333333 -> 0.40416664
emissions.as_gtco2eq: 55.31417 -> 39.762833

<img width="357" alt="2035-2040" src="https://github.com/user-attachments/assets/aebe55ae-a9a6-4b3d-916a-37dc191330cd">

[2040]
political_capital: 8 -> 9
protected_land: 0.40416664 -> 0.56999993
emissions.as_gtco2eq: 3**9.762833** -> 22.85015 (discrepancy in the single digits and higher from here on out)

<img width="328" alt="2040-2045" src="https://github.com/user-attachments/assets/03213169-53fb-4cbf-a8b0-c8cbc1916615">

[2045]
political_capital: 9 -> 189
emissions.as_gtco2eq: **22.85015** -> -0.6647185

<img width="268" alt="2045-2050" src="https://github.com/user-attachments/assets/57a35ebf-25c6-4166-8799-96352d627dcf">

[2050]
political_capital: 189 -> 210
protected_land: 0.56999993 -> 0.61999995
emissions.as_gtco2eq: -0.6647185 -> -14.41661

<img width="272" alt="2050-2055" src="https://github.com/user-attachments/assets/beeed44b-a21f-4554-8b92-136e5f4734fb">

[2055]
political_capital: 210 -> 364
emissions.as_gtco2eq: -14.41661 -> -24.015253

[HES Summary 2.txt](https://github.com/user-attachments/files/16788576/HES.Summary.2.txt)

**Comment by frnsys** [comment]
thanks for the report. I've investigated a bit and have a lead about what could be going on, but hard to be sure right now.

Emissions results under a few different scenarios below...

to make things easier I tried a few runs where I removed the energy usage of DAC.

```
No DAC
2022=51.6
2025=55.6
2030=62.7
2035=70.1
2040=77.6

DAC, no upgrades
2022=51.6
2025=56.2
2030=63.9
2035=71.3
2040=78.8

DAC, no upgrades, removed DAC energy usage
2022=51.6
2025=54.9
2030=61.2
2035=68.6
2040=76.1

DAC, one upgrade, removed DAC energy usage
2022=51.6
2025=54.9
2030=61.2 Finished
2035=68.6 Upgraded
  then in planning: 67.1 (68.6 - 1.5)
2040=74.6

DAC, two upgrades, removed DAC energy usage
2022=51.6
2025=54.9
2030=61.2 Finished
2035=68.6 Upgraded
  then in planning: 67.1 (68.6 - 1.5)
2040=74.6 Upgraded
  then in planning: 73.1 (74.6 - 1.5)
```

The console output and the report/planning HUD numbers matched each time. In the last two example s(where I upgraded DAC) the report and console both report 68.6 and then after you go to the next planning screen, the HUD reports 67.1, I'm pretty sure this is just because the upgrade effect (an additional 1.5 emissions reduction) isn't taken into account until after the report. 

Does that sound more or less like what might be happening on your end?

**Comment by sgitkene** [comment]
I did a run leaving out any projects that said to reduce ghg directly. The only one I took and kept upgrading is DAC. However, I don't think DAC is the culprit anymore. I noticed a discrepancy between the stats screen and the summaries and the console output. It seems a different value is taken at each point. I'm now just pretty certain that something else besides possibly DAC is wrong.

[2035]
political_capital: 0 -> 6
protected_land: 0.1 -> 0.33750004
emissions.as_gtco2eq: 41.35248 -> 32.71087

<img width="248" alt="2030-2035" src="https://github.com/user-attachments/assets/700ac125-41ba-4c46-95a9-d876940b3690">

The year end summary indicates 32.0 (0.7 difference from console)

<img width="503" alt="2035-land" src="https://github.com/user-attachments/assets/a8542753-ad12-4829-bcb2-61a566ecd1d9">

The stats screen has a wildly different number at 24.0Gt.

Not sure if it helps with anything but here the rest of the screenshots of that run as well as the full "history" summary and savegame (as text file exported from storage): 
[run4.zip](https://github.com/user-attachments/files/16822787/run4.zip)

**Comment by sgitkene** [comment]
when I do the same thing as you (no DAC) and just click ready every cycle, I get the following:

[2025]
emissions.as_gtco2eq: 51.579174 -> 55.642757
[2030]
emissions.as_gtco2eq: 55.642757 -> 64.04519
[2035]
emissions.as_gtco2eq: 64.04519 -> 71.67728
(game over)

The values on the stats screen and reports all match up.

<img width="307" alt="2022-2025" src="https://github.com/user-attachments/assets/5fe363bc-6036-4f7f-bd22-5e992a9a709a">
<img width="502" alt="2022-emissions" src="https://github.com/user-attachments/assets/8b29fa11-840f-45df-8cae-c2e58711ebdd">
<img width="499" alt="2022-land" src="https://github.com/user-attachments/assets/6e62092b-e3f2-421a-8be5-5414e99eb695">
<img width="273" alt="2025-2030" src="https://github.com/user-attachments/assets/0d9ddd95-1feb-48ab-a635-ebd4dd0f9361">
<img width="484" alt="2025-emissions" src="https://github.com/user-attachments/assets/72d19f03-111b-470c-9db0-447de30ea741">
<img width="262" alt="2030-2035" src="https://github.com/user-attachments/assets/76c7df8a-5599-4a34-af9d-b67f29d237b5">
<img width="499" alt="2030-emissions" src="https://github.com/user-attachments/assets/1cbb4801-2422-42d0-b0d9-763be4281345">

**Comment by sgitkene** [comment]
The discrepancies show up when changing the production mix:

<img width="490" alt="2022-emissions" src="https://github.com/user-attachments/assets/1c8990ed-e0e5-4e28-ac52-0ab3f2fc4f99">

2022 stats.

<img width="277" alt="2022-2025" src="https://github.com/user-attachments/assets/bb587960-6067-476e-800f-5d62ec56ad52">

transition 2022-2025
Console:
```
[2025]
emissions.as_gtco2eq: 51.579174 -> 55.642757
```

<img width="496" alt="2025-emissions" src="https://github.com/user-attachments/assets/ec1b1774-54bc-4aa0-ba51-3f6ccdd96e01">

2025 stats.

<img width="267" alt="2025-2030" src="https://github.com/user-attachments/assets/2f099a57-dc8b-486a-884f-2d1dee0103b7">

transition 2025-2030
Console:
```
[2030]
political_capital: 100 -> 74
emissions.as_gtco2eq: 55.642757 -> 109.67238
```

<img width="502" alt="2030-emissions" src="https://github.com/user-attachments/assets/18b4004c-e43d-44d4-8195-a730695274b4">

2030 stats.

<img width="272" alt="2030-2035" src="https://github.com/user-attachments/assets/0e57c2f4-5080-461f-99c1-ae318bdbe3e1">

transition 2030-2035.
Console:
```
[2035]
political_capital: 74 -> 50
emissions.as_gtco2eq: 109.67238 -> 136.01736
```
(Game over)

**Comment by frnsys** [comment]
I think this was due to process mix changes being applied *after* the report phase so they weren't properly reflected in the report. So this may be fixed now.

**Comment by frnsys** [comment]
Should be live now !

**Comment by sgitkene** [comment]
seems to work now 🥳
