### ISSUE TITLE
Get "exhausted all political capital" or game over when loading the game with 0 spare political capital

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#300]
I managed to get 50 additional political capital in 2022 by using up all my political capital, going through the tags to generate a save, reloading page, then "continuing" with the last save.

![image](https://github.com/user-attachments/assets/430b25b5-c743-4b2c-b429-24b89c7b99bc)
50 available political capital despite using it all up in projects.

I believe this is due to how the event is scheduled. When loading, there seems to be the phase that checks for if one has 0 political capital and thus firing the related event.

When I use up my political capital again and reload the save, I get the following game-over screen:

![image](https://github.com/user-attachments/assets/2b9a9b75-45d1-4da9-9f0d-ab2abc0567df)
Game over without any history.

Any% speedrun world record :)

**Comment by sgitkene** [comment]
I just checked the steam version, it seems to be unaffected because the respective transition isn't done when loading.

![image](https://github.com/user-attachments/assets/b185e67d-eaf4-442e-8262-2b23a3297210)
This screen, specifically.

**Comment by frnsys** [comment]
ah good catch. Originally loading a saved game put you directly into the planning page, which I guess I'd done to avoid this exact problem, but that was crashing something so I switched it to this interstitial phase instead. But it looks like whatever bug was there originally is gone now, so I can change it back to the old behavior. thanks!
