### ISSUE TITLE
Adding a new project in the editor seems to disturb existing projects below (visual glitch only?)

### ISSUE THREAD

**Issue by sgitkene** [frnsys/half_earth#302]
After I added a new project, I noticed that the next project below was reset.

![image](https://github.com/user-attachments/assets/87bdc9ae-a89d-46de-96e7-cfe1ddbefba9)

In fact, it will get similar adjustments as the new project just created. Some of its own settings are pushed down into the next project:

![image](https://github.com/user-attachments/assets/25a2d87a-2fb7-4061-ad00-f70b967ce5e1)

This may be only a presentation issue. Exporting the project, reloading the page, and then importing it again I don't see the changes to the project below anymore.

**Comment by frnsys** [comment]
so I'd actually fixed this awhile ago but forgot to update the site--should be good now
