### ISSUE TITLE
Biodiversity not winable

### ISSUE THREAD

**Issue by pabachmann** [frnsys/half_earth#307]
Even though I put all efforts into lowering the biodiversity pressure, I always end up with around 2-10 points above the threshold... Is this a bug or am I missing something? I used to be able to get it way lower with the same strategies...

**Comment by Ataraxta** [comment]
I was having the same issue, and it was due to Hempcrete.
I was able to complete by avoiding that research

**Comment by frnsys** [comment]
Thanks for catching that, I'll update with corrected land-use values for hempcrete.

**Comment by pabachmann** [comment]
I mus say I tried without hempcrete and still ended up around 22 for biodiversity with nothing left to decrease the biodiversity pressure. I even omitted any land power generation, going only for floating wind turbines. Not sure what the issue is, there just seem to be a lot more (random) catastrophes that bring up the pressure so much that it's not winable. Maybe I do something wrong in the early game and that's why I get these catastrophes but it wasnt like this before...
