### ISSUE TITLE
Production shortages because of a bug

### ISSUE THREAD

**Issue by qweertz** [frnsys/half_earth#311]
First of all: I greatly appreciate the work you have done with this game, it has become one of my favourite leftist political sims (right next to the works of Nostalgames aka. Kremlingames). Even if I don't agree with the depiction (or lack thereof) of some political currents/assessment of some technologies and such, the book has a prominent place on my theory reading list!

Now to the report:
Some producers just stop putting out anything in 2030 like most fuel ones and electricity just stops being produced altogether. I have attached the game history and hope this issue is helpful.  
I'll try to respond quickly to any follow-up questions ^.^

<details>
<summary>Game History</summary>

Your History
------------

[2025]
political_capital: 100 -> 1
protected_land: 0.1 -> 0.16000001
emissions.as_gtco2eq: 51.579174 -> 67.72101
production:
  Fuel: 88.49 -> 113.60
  Electricity: 26.04 -> 62.92
  Plant Calories: 341.83 -> 353.96
  Animal Calories: 72.91 -> 69.82
output_demand:
  Fuel: 88.49 -> 113.60
  Electricity: 26.04 -> 62.92
  Plant Calories: 341.83 -> 353.96
  Animal Calories: 72.91 -> 69.82
production_surplus:
  Plant Calories: 0.00 -> 0.00
resource_demand:
  Land: 50.61 -> 63.07
  Water: 21540.55 -> 24263.48
  Electricity: 25.38 -> 26.63
  Fuel: 86.66 -> 91.90
resources:
  Land: 93.60 -> 87.36
  Electricity: 113.88 -> 62.92
  Fuel: 175.15 -> 113.60
resource_surplus:
  Land: 42.99 -> 24.29
  Water: 23959.45 -> 21236.52
  Electricity: 88.49 -> 36.28
  Fuel: 88.49 -> 21.70
feedstocks:
  Oil: 809.19 -> 763.55
  Coal: 1264793.50 -> 1236861.00
  Uranium: 7.93 -> 7.75
  Natural Gas: 714006.88 -> 698528.50
flags:
  Added "SkipTutorial"
events:
  Added "Intro Cutscene"
  Added "Planning Intro"
  Added "Flooding - Intro"
  Added "Wildfires - Intro"
  Added "Wildfires"
  Added "Wildfires"
  Added "Flooding"
extinction_rate: 90.188515 -> 88.51046
temperature: 1.1 -> 1.4240979
outlook: 30.0 -> 29.190592
projects:
  Next-Gen Solar PV:
    status: Inactive -> Building
  Sewage Treatment Plants:
    status: Inactive -> Building
  Expand Nature Preserves:
    status: Inactive -> Building
  Green Hydrogen:
    status: Inactive -> Building
  Fanonist Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Utopian Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Ecofeminist Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Phage Therapy:
    status: Inactive -> Building
  Animal Liberationist Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  High-Density Batteries:
    status: Inactive -> Building
  Expand Public Transit:
    status: Inactive -> Building
  Champagne Socialism:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Biofabrication:
    status: Inactive -> Building
  Electric-Arc Furnaces:
    status: Inactive -> Building
  Wooden Skyscrapers:
    status: Inactive -> Building
  Passive Building Mandate & Retrofit:
    status: Inactive -> Building
  Indigenous Sovereignty:
    status: Inactive -> Building
  Environmentalist Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Energy Conservation Campaign:
    status: Inactive -> Building
  Universal Family Planning:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Floating Wind Turbines:
    status: Inactive -> Building
  'Green' Container Ships:
    status: Inactive -> Building
  Pedestrian and Bike-Friendly Cities:
    status: Inactive -> Building
  Accelerationist Curriculum:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Remediate and Protect Ecosystems:
    status: Inactive -> Building
  Perennial Cereals:
    status: Inactive -> Building
processes:
  Solar PV:
    mix_share: 1 -> 3
  Nuclear Power:
    mix_share: 2 -> 3
  Smallholder Farms:
    mix_share: 6 -> 8
  Blue Hydrogen:
    mix_share: 0 -> 1
  Industrial Crop Ag:
    mix_share: 14 -> 9
  Terrestrial Wind Power:
    mix_share: 1 -> 3
  Grey Hydrogen:
    mix_share: 0 -> 1
  Coal Power Generation:
    mix_share: 7 -> 3
  Organic Livestock Ag:
    mix_share: 0 -> 5
  Industrial Livestock Ag:
    mix_share: 20 -> 15
  Petroleum Power Gen:
    mix_share: 1 -> 0
  Biofuels:
    mix_share: 3 -> 4
  Petroleum:
    mix_share: 11 -> 8
  Organic Crop Ag:
    mix_share: 0 -> 2
  Vertical Farming:
    mix_share: 0 -> 1
Production Mix:
  [Fuel]
    Biofuels:4
    Blue Hydrogen:1
    Coal:2
    Grey Hydrogen:1
    Natural Gas:4
    Petroleum:8
  [Electricity]
    Coal Power Generation:3
    Hydropower:3
    Natural Gas Power Gen:5
    Nuclear Power:3
    Solar PV:3
    Terrestrial Wind Power:3
  [Plant Calories]
    Industrial Crop Ag:9
    Organic Crop Ag:2
    Smallholder Farms:8
    Vertical Farming:1
  [Animal Calories]
    Industrial Livestock Ag:15
    Organic Livestock Ag:5

[2030]
political_capital: 1 -> 21
protected_land: 0.16000001 -> 0.35666662
emissions.as_gtco2eq: 67.72101 -> 17.02229
production:
  Fuel: 113.60 -> 36.95
  Electricity: 62.92 -> 0.00
  Plant Calories: 353.96 -> 184.32
  Animal Calories: 69.82 -> 71.06
output_demand:
  Fuel: 113.60 -> 123.18
  Electricity: 62.92 -> 103.04
  Plant Calories: 353.96 -> 368.65
  Animal Calories: 69.82 -> 73.43
production_surplus:
  Fuel: 0.00 -> -86.23
  Electricity: 0.00 -> -103.04
  Plant Calories: 0.00 -> -184.32
  Animal Calories: 0.00 -> -2.38
resource_demand:
  Land: 63.07 -> 77.60
  Water: 24263.48 -> 26646.24
  Electricity: 26.63 -> 28.32
  Fuel: 91.90 -> 99.59
resources:
  Land: 87.36 -> 66.91
  Electricity: 62.92 -> 0.00
  Fuel: 113.60 -> 36.95
resource_surplus:
  Land: 24.29 -> -10.69
  Water: 21236.52 -> 18853.76
  Electricity: 36.28 -> -28.32
  Fuel: 21.70 -> -62.64
feedstocks:
  Oil: 763.55 -> 692.77
  Coal: 1236861.00 -> 1182365.62
  Uranium: 7.75 -> 6.64
  Natural Gas: 698528.50 -> 657148.06
flags:
  Added "BailedOut"
events:
  Added "Bail Out"
  Added "Ally - The Environmentalist"
  Added "Ally - The Fanonist"
  Added "Ally - The Utopian"
  Added "Book Extract - Havana"
  Added "NPC guidance - Geoengineer"
  Added "Eutrophication - A Global Problem"
  Added "New Mosquito-Borne Disease"
  Added "Locust Infestation"
  Added "More and More Mega-Dams"
  Added "Disease Outbreak"
  Added "Mountain Gorilla Declared Extinct"
  Added "Aurochs Return to the Eurasian Plains"
  Added "Too Hot to Work"
  Added "Wheat Rust Destroys Harvest"
  Added "Disease Outbreak"
  Added "Disease Outbreak"
  Added "Wildfires"
  Added "Indigenous Nations Block Oil Infrastructure"
  Added "Silent Spring"
  Added "Wildfires - Smoke"
  Added "Massive Jellyfish Blooms"
  Added "Great Barrier Reef Dead"
  Added "Deadly Heat Dome"
  Added "Brownouts - Intro"
  Added "Severe Hurricane - Intro"
extinction_rate: 88.51046 -> 93.97499
temperature: 1.4240979 -> 1.5909795
outlook: 29.190592 -> 18.8805
projects:
  Feminist Science and Technology Studies:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Reintroduce Apex Predators:
    status: Inactive -> Building
  Indigenous Sovereignty:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Hempcrete:
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Energy Conservation Campaign:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Marine Protected Areas:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Search for Extraterrestrial Life:
    status: Inactive -> Building
processes:
  Solar PV:
    mix_share: 3 -> 4
  Nuclear Power:
    mix_share: 3 -> 5
  Industrial Crop Ag:
    mix_share: 9 -> 5
  Coal Power Generation:
    mix_share: 3 -> 0
  Organic Livestock Ag:
    mix_share: 5 -> 9
  Industrial Livestock Ag:
    mix_share: 15 -> 11
  Organic Crop Ag:
    mix_share: 2 -> 5
  Vertical Farming:
    mix_share: 1 -> 2
Production Mix:
  [Fuel]
    Biofuels:4
    Blue Hydrogen:1
    Coal:2
    Grey Hydrogen:1
    Natural Gas:4
    Petroleum:8
  [Electricity]
    Hydropower:3
    Natural Gas Power Gen:5
    Nuclear Power:5
    Solar PV:4
    Terrestrial Wind Power:3
  [Plant Calories]
    Industrial Crop Ag:5
    Organic Crop Ag:5
    Smallholder Farms:8
    Vertical Farming:2
  [Animal Calories]
    Industrial Livestock Ag:11
    Organic Livestock Ag:9

[2035]
political_capital: 21 -> 140
protected_land: 0.35666662 -> 0.54875004
emissions.as_gtco2eq: 17.02229 -> -1.9306451
production:
  Fuel: 36.95 -> 0.00
  Plant Calories: 184.32 -> 218.04
  Animal Calories: 71.06 -> 26.98
output_demand:
  Fuel: 123.18 -> 151.57
  Electricity: 103.04 -> 119.06
  Plant Calories: 368.65 -> 436.08
  Animal Calories: 73.43 -> 39.38
production_surplus:
  Fuel: -86.23 -> -151.57
  Electricity: -103.04 -> -119.06
  Plant Calories: -184.32 -> -218.04
  Animal Calories: -2.38 -> -12.40
resource_demand:
  Land: 77.60 -> 60.06
  Water: 26646.24 -> 26208.74
  Electricity: 28.32 -> 30.66
  Fuel: 99.59 -> 91.90
resources:
  Land: 66.91 -> 46.93
  Fuel: 36.95 -> 0.00
resource_surplus:
  Land: -10.69 -> -13.13
  Water: 18853.76 -> 19291.26
  Electricity: -28.32 -> -30.66
  Fuel: -62.64 -> -91.90
feedstocks:
  Oil: 692.77 -> 648.83
  Coal: 1182365.62 -> 1152770.62
  Uranium: 6.64 -> 5.45
  Natural Gas: 657148.06 -> 621912.06
flags:
  Added "LaborSabotage"
  Added "FastDevelopment"
  Added "MoreLabor"
events:
  Added "Production Shortage"
  Added "Nemesis - The Consumerist"
  Added "Ally - The Ecofeminist"
  Added "Are We Preserving Too Much Land?"
  Added "NPC guidance - Ecologist"
  Added "Blackouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Brownouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Blackouts"
  Added "Severe Flooding - Intro"
  Added "Bird-Watching Craze"
  Added "Nuclear Waste"
  Added "Mendel-Mania"
  Added "Uranium Running Out"
  Added "Oil Pollution Causes High Infant Mortality"
  Added "Heatwaves - Intro"
  Added "Sabotage"
  Added "Severe Hurricane"
  Added "Famine - Intro"
  Added "NIMBYs"
  Added "Dancing Plague"
  Added "Earth Liberation Front - (Re)Formation"
  Added "Half-Earth"
  Added "Brownouts"
  Added "Brownouts"
  Added "Brownouts"
  Added "Famine"
  Added "Blackouts"
  Added "Brownouts"
  Added "Famine"
  Added "Famine"
  Added "Brownouts"
  Added "Blackouts"
  Added "Brownouts"
  Added "Brownouts"
  Added "Blackouts"
  Added "Famine"
  Added "Blackouts"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Blackouts"
  Added "Blackouts"
  Added "Blackouts"
  Added "Blackouts"
  Added "Blackouts"
  Added "Famine"
  Added "Brownouts"
  Added "Famine"
  Added "Severe Hurricane"
  Added "Blackouts"
  Added "Famine"
  Added "Brownouts"
  Added "Famine"
  Added "Brownouts"
  Added "Severe Hurricane"
  Added "Blackouts"
  Added "Brownouts"
  Added "Ash Dieback"
  Added "Famine"
  Added "Heatwaves"
  Added "Heatwaves"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Severe Flooding"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Severe Hurricane"
  Added "Famine"
  Added "Severe Hurricane"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Famine"
  Added "Pollinator - Decline"
  Added "New Cuisine"
  Added "Vaquita Porpoise Declared Extinct"
extinction_rate: 93.97499 -> 69.980034
temperature: 1.5909795 -> 1.6988114
outlook: 18.8805 -> 38.616962
projects:
  Carbon Capture and Sequestration:
    status: Inactive -> Building
  Sewage Treatment Plants:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Expand Nature Preserves:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Green Hydrogen:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Cellular Meat:
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Reconcile Town and Country:
    status: Inactive -> Building
  Drought-Resistant Crops:
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Carbon-Negative Concrete:
    status: Inactive -> Building
  High-Density Batteries:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Factory Farming Reform:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Remove Fetters on the Forces of Production!:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Multistrata Agroforestry:
    status: Inactive -> Building
  Restrict Air Travel:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Co-Generation:
    status: Inactive -> Building
  Stakhanovite Shock Workers:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Ban High-Seas Fishing:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Reintroduce Apex Predators:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Electric-Arc Furnaces:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Coastal Wetland Protection and Restoration:
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Meatless Mondays:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Green Roofs:
    status: Inactive -> Building
  Biochar:
    status: Inactive -> Building
  Ban Outdoor Cats:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Abolish Prisons:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  3rd Generation Biofuels:
    status: Inactive -> Building
  (Mostly) Full Automation:
    status: Inactive -> Building
  Biosphere 3:
    status: Inactive -> Building
  Masculinity De-Tox:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Alternative Refrigerants:
    status: Inactive -> Building
  Flexitarian:
    status: Inactive -> Active
    active_outcome: None -> Some(0)
  Restore Desert Habitats:
    status: Inactive -> Building
  Ecosocialist Video Game:
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Compost:
    status: Inactive -> Building
  Floating Wind Turbines:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  'Green' Container Ships:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Advances in Ecosystem Modelling:
    status: Inactive -> Building
  Search for Extraterrestrial Life:
    status: Building -> Finished
    active_outcome: None -> Some(0)
  Long-Range Electric Aviation:
    status: Inactive -> Building
  Bioenergy Carbon Capture and Sequestration (BECCS):
    status: Inactive -> Finished
    active_outcome: None -> Some(0)
  Perennial Cereals:
    status: Building -> Finished
    active_outcome: None -> Some(0)
processes:
  Solar PV:
    mix_share: 4 -> 6
  Blue Hydrogen:
    mix_share: 1 -> 3
  Hydropower:
    mix_share: 3 -> 2
  Industrial Crop Ag:
    mix_share: 5 -> 0
  Grey Hydrogen:
    mix_share: 1 -> 2
  Organic Livestock Ag:
    mix_share: 9 -> 14
  Coal:
    mix_share: 2 -> 0
  Natural Gas Power Gen:
    mix_share: 5 -> 4
  Industrial Livestock Ag:
    mix_share: 11 -> 6
  Natural Gas:
    mix_share: 4 -> 6
  Petroleum:
    mix_share: 8 -> 5
  Organic Crop Ag:
    mix_share: 5 -> 10
Production Mix:
  [Fuel]
    Biofuels:4
    Blue Hydrogen:3
    Grey Hydrogen:2
    Natural Gas:6
    Petroleum:5
  [Electricity]
    Hydropower:2
    Natural Gas Power Gen:4
    Nuclear Power:5
    Solar PV:6
    Terrestrial Wind Power:3
  [Plant Calories]
    Organic Crop Ag:10
    Smallholder Farms:8
    Vertical Farming:2
  [Animal Calories]
    Industrial Livestock Ag:6
    Organic Livestock Ag:14

</details>

**Comment by frnsys** [comment]
thanks for the report! This sounds like it might be the same as #310, which I'm working on right now. hope to have a fix up soon.

**Comment by qweertz** [comment]
ah, sorry for the duplicate then. I thought that this would be different since it happened just 5 years into the game, while #310 seemed like a late-game thing

**Comment by frnsys** [comment]
The bug ended up being a more general problem with how production was calculated so I believe it's the same issue, but if you still have the problem please feel free to re-open and I'll take another look!
